FROM node:20-bullseye

WORKDIR /app

# Add company CA
COPY company-ca.crt /usr/local/share/ca-certificates/company-ca.crt
RUN update-ca-certificates

# Tell Node to trust the company CA
ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/company-ca.crt

# Install envsubst
RUN apt-get update && apt-get install -y gettext

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

# CMD ["npx", "vite", "--host"]
# CMD ["npm","run","dev","--","--host"]

# Generate env.js at runtime, then start dev server
CMD sh -c "envsubst < public/env.template.js > public/env.js && npm run dev -- --host"
