FROM golang:1.24.2-alpine

WORKDIR /app

# Install certificates package
RUN apk add --no-cache ca-certificates

COPY company-ca.crt /usr/local/share/ca-certificates/company-ca.crt
RUN update-ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["go", "run", "main.go"]
