FROM golang:1.24-alpine as build

WORKDIR /app

COPY company-ca.crt /usr/local/share/ca-certificates/company-ca.crt
RUN update-ca-certificates

# Copy dependency files first
COPY go.mod go.sum ./
RUN go mod download

# Now copy full source
COPY . .

# Build binary
RUN go build -o api-golang

# Production stage
FROM alpine:latest

WORKDIR /app
COPY --from=build /app/api-golang .

EXPOSE 8080
CMD ["./api-golang"]
